# coding: utf-8

"""
    Clever API

    The Clever API  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.school_enrollment import SchoolEnrollment  # noqa: E501
from swagger_client.rest import ApiException


class TestSchoolEnrollment(unittest.TestCase):
    """SchoolEnrollment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchoolEnrollment(self):
        """Test SchoolEnrollment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.school_enrollment.SchoolEnrollment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
